// <auto-generated />
using System;
using Final_Mission.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Final_Mission.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220419221719_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Final_Mission.Models.Quote", b =>
                {
                    b.Property<int>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Citation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.HasKey("QuoteId");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            QuoteId = 1,
                            Author = "Brennan Williams",
                            Citation = "Book of mormon",
                            Date = new DateTime(2022, 4, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteText = "We are all sons and daughters of a loving heavenly father",
                            Subject = "Book of Mormon History"
                        },
                        new
                        {
                            QuoteId = 2,
                            Author = "Brennan Williams",
                            Citation = "Book of mormon",
                            Date = new DateTime(2022, 4, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteText = "We are all sons and daughters of a loving heavenly father",
                            Subject = "Book of Mormon History"
                        },
                        new
                        {
                            QuoteId = 3,
                            Author = "Brennan Williams",
                            Citation = "Book of mormon",
                            Date = new DateTime(2022, 4, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            QuoteText = "We are all sons and daughters of a loving heavenly father",
                            Subject = "Book of Mormon History"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
